### ISSUE TITLE
Error with colcon build

### ISSUE THREAD

**Issue by GabrieleCesare** [jeremyfix/ros2_parrot_arsdk#1]
Hi, I am trying to install the ros2_parrot_arsdk package, but I keep getting the following error:

gabrielecesare@gabrielecesare-Desktop:~/temp_ws$ colcon build --packages-select ros2_parrot_arsdk
Starting >>> ros2_parrot_arsdk
--- stderr: ros2_parrot_arsdk                                

Fetching:  0% (0/31) 0:00 | None
etching:  0% (0/31) 0:00 | warming up
etching:  0% (0/31) 0:00 | ..working..
etching:  0% (0/31) 0:01 | ..working..
etching:  0% (0/31) 0:01 | 4 jobs | 0:00 Alchemy @ build/alchemy
etching:  0% (0/31) 0:02 | 4 jobs | 0:00 Alchemy @ build/alchemy
etching:  0% (0/31) 0:02 | 4 jobs | 0:00 libARMedia @ packages/libARMedia
etching:  0% (0/31) 0:03 | 4 jobs | 0:00 libARMedia @ packages/libARMedia
etching:  0% (0/31) 0:03 | 4 jobs | 0:01 libARMedia @ packages/libARMedia
etching:  0% (0/31) 0:04 | 4 jobs | 0:01 libARMedia @ packages/libARMedia
etching:  0% (0/31) 0:04 | 4 jobs | 0:02 libARMedia @ packages/libARMedia
etching:  0% (0/31) 0:05 | 4 jobs | 0:02 libARMedia @ packages/libARMedia
etching:  0% (0/31) 0:05 | 4 jobs | 0:00 libARNetwork @ packages/libARNetwork
etching:  3% (1/31) 0:05 | 4 jobs | 0:00 libARNetwork @ packages/libARNetwork
etching:  6% (2/31) 0:05 | 4 jobs | 0:00 libARNetwork @ packages/libARNetwork
etching:  9% (3/31) 0:05 | 4 jobs | 0:00 libARNetwork @ packages/libARNetwork
etching: 12% (4/31) 0:05 | 4 jobs | 0:00 libARNetwork @ packages/libARNetwork
etching: 12% (4/31) 0:06 | 4 jobs | 0:00 libARNetwork @ packages/libARNetwork
etching: 12% (4/31) 0:06 | 4 jobs | 0:01 libARDataTransfer @ packages/libARDataTransfer
etching: 12% (4/31) 0:07 | 4 jobs | 0:01 libARDataTransfer @ packages/libARDataTransfer
etching: 12% (4/31) 0:07 | 4 jobs | 0:02 libARDataTransfer @ packages/libARDataTransfer
etching: 16% (5/31) 0:07 | 4 jobs | 0:02 libARDataTransfer @ packages/libARDataTransfer
etching: 19% (6/31) 0:07 | 4 jobs | 0:02 libARDataTransfer @ packages/libARDataTransfer
etching: 22% (7/31) 0:07 | 4 jobs | 0:02 libARDataTransfer @ packages/libARDataTransfer
etching: 25% (8/31) 0:07 | 4 jobs | 0:02 libARDataTransfer @ packages/libARDataTransfer
etching: 25% (8/31) 0:08 | 4 jobs | 0:02 libARDataTransfer @ packages/libARDataTransfer
etching: 25% (8/31) 0:08 | 4 jobs | 0:03 libARDataTransfer @ packages/libARDataTransfer
etching: 29% (9/31) 0:08 | 4 jobs | 0:03 libARDataTransfer @ packages/libARDataTransfer
etching: 32% (10/31) 0:08 | 4 jobs | 0:03 libARDataTransfer @ packages/libARDataTransfer
etching: 35% (11/31) 0:08 | 4 jobs | 0:03 libARDataTransfer @ packages/libARDataTransfer
etching: 38% (12/31) 0:08 | 4 jobs | 0:03 libARDataTransfer @ packages/libARDataTransfer
etching: 38% (12/31) 0:09 | 4 jobs | 0:03 libARDataTransfer @ packages/libARDataTransfer
etching: 38% (12/31) 0:09 | 4 jobs | 0:04 libARDataTransfer @ packages/libARDataTransfer
etching: 38% (12/31) 0:10 | 4 jobs | 0:04 libARDataTransfer @ packages/libARDataTransfer
etching: 38% (12/31) 0:10 | 4 jobs | 0:02 libARUtils @ packages/libARUtils
etching: 38% (12/31) 0:11 | 4 jobs | 0:02 libARUtils @ packages/libARUtils
etching: 38% (12/31) 0:11 | 4 jobs | 0:01 libARDiscovery @ packages/libARDiscovery
etching: 41% (13/31) 0:11 | 4 jobs | 0:01 libARDiscovery @ packages/libARDiscovery
etching: 45% (14/31) 0:11 | 4 jobs | 0:01 libARDiscovery @ packages/libARDiscovery
etching: 48% (15/31) 0:11 | 4 jobs | 0:01 libARDiscovery @ packages/libARDiscovery
etching: 51% (16/31) 0:11 | 4 jobs | 0:01 libARDiscovery @ packages/libARDiscovery
etching: 51% (16/31) 0:12 | 4 jobs | 0:01 libARDiscovery @ packages/libARDiscovery
etching: 51% (16/31) 0:12 | 4 jobs | 0:00 libsdp @ packages/libsdp
etching: 51% (16/31) 0:13 | 4 jobs | 0:00 libsdp @ packages/libsdp
etching: 51% (16/31) 0:13 | 4 jobs | 0:01 mavlink.git @ packages/mavlink
etching: 54% (17/31) 0:13 | 4 jobs | 0:01 mavlink.git @ packages/mavlink
etching: 58% (18/31) 0:13 | 4 jobs | 0:01 mavlink.git @ packages/mavlink
etching: 61% (19/31) 0:13 | 4 jobs | 0:01 mavlink.git @ packages/mavlink
etching: 64% (20/31) 0:13 | 4 jobs | 0:01 mavlink.git @ packages/mavlink
etching: 64% (20/31) 0:14 | 4 jobs | 0:01 mavlink.git @ packages/mavlink
etching: 64% (20/31) 0:14 | 3 jobs | 0:02 libARUpdater @ packages/libARUpdater
etching: 67% (21/31) 0:14 | 3 jobs | 0:02 libARUpdater @ packages/libARUpdater
etching: 70% (22/31) 0:14 | 3 jobs | 0:02 libARUpdater @ packages/libARUpdater
etching: 74% (23/31) 0:14 | 3 jobs | 0:02 libARUpdater @ packages/libARUpdater
etching: 77% (24/31) 0:14 | 3 jobs | 0:02 libARUpdater @ packages/libARUpdater
etching: 80% (25/31) 0:14 | 3 jobs | 0:02 libARUpdater @ packages/libARUpdater
etching: 83% (26/31) 0:14 | 3 jobs | 0:02 libARUpdater @ packages/libARUpdater
etching: 87% (27/31) 0:14 | 3 jobs | 0:02 libARUpdater @ packages/libARUpdater
etching: 90% (28/31) 0:14 | 3 jobs | 0:02 libARUpdater @ packages/libARUpdater
etching: 90% (28/31) 0:15 | 3 jobs | 0:02 libARUpdater @ packages/libARUpdater
etching: 90% (28/31) 0:15 | 1 job | 0:00 arsdk_products @ products/arsdk
etching: 93% (29/31) 0:15 | 1 job | 0:00 arsdk_products @ products/arsdk
etching: 96% (30/31) 0:15 | 1 job | 0:00 arsdk_products @ products/arsdk
etching: 100% (31/31) 0:15 | 1 job | 0:00 arsdk_products @ products/arsdk
etching: 100% (31/31), done in 15.825s..[I] Starting task 'build-sdk'
[I] In '/home/gabrielecesare/temp_ws/build/ros2_parrot_arsdk/parrot_arsdk': ALCHEMY_TARGET_CONFIG_DIR="/home/gabrielecesare/temp_ws/build/ros2_parrot_arsdk/parrot_arsdk/products/arsdk/native/config" ALCHEMY_TARGET_OUT="/home/gabrielecesare/temp_ws/build/ros2_parrot_arsdk/parrot_arsdk/out/arsdk-native" ALCHEMY_TARGET_PRODUCT="arsdk" ALCHEMY_TARGET_PRODUCT_VARIANT="native" ALCHEMY_TARGET_SCAN_ADD_DIRS=" /home/gabrielecesare/temp_ws/build/ros2_parrot_arsdk/parrot_arsdk/packages" ALCHEMY_TARGET_SCAN_PRUNE_DIRS=" /home/gabrielecesare/temp_ws/build/ros2_parrot_arsdk/parrot_arsdk" ALCHEMY_USE_COLORS="1" ALCHEMY_WORKSPACE_DIR="/home/gabrielecesare/temp_ws/build/ros2_parrot_arsdk/parrot_arsdk" PARROT_BUILD_PROP_GROUP="drones" PARROT_BUILD_PROP_PRODUCT="arsdk" PARROT_BUILD_PROP_PROJECT="arsdk" PARROT_BUILD_PROP_UID="arsdk-native-20240511-1345-0.0.0" PARROT_BUILD_PROP_VARIANT="native" PARROT_BUILD_PROP_VERSION="0.0.0" /home/gabrielecesare/temp_ws/build/ros2_parrot_arsdk/parrot_arsdk/build/alchemy/scripts/alchemake -j 20 all
make[3]: warning: -j20 forced in submake: resetting jobserver mode.
Scanning /home/gabrielecesare/temp_ws/build/ros2_parrot_arsdk/parrot_arsdk/packages for makefiles...
In file included from /usr/include/string.h:535,
                 from packages/libpomp/src/pomp_priv.h:43,
                 from packages/libpomp/src/pomp_addr.c:35:
In function ‘strncpy’,
    inlined from ‘pomp_addr_parse’ at packages/libpomp/src/pomp_addr.c:125:3:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:95:10: warning: ‘__builtin_strncpy’ specified bound 108 equals destination size [-Wstringop-truncation]
   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   96 |                                   __glibc_objsize (__dest));
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~
/bin/bash: line 1: python: command not found
make[3]: *** [/home/gabrielecesare/temp_ws/build/ros2_parrot_arsdk/parrot_arsdk/build/alchemy/main.mk:306: /home/gabrielecesare/temp_ws/build/ros2_parrot_arsdk/parrot_arsdk/out/arsdk-native/build/libARMavlink/parrot.xml.done] Error 127
make[3]: *** Waiting for unfinished jobs....
[E] Task 'build-sdk' failed (Command failed (returncode=2))
gmake[2]: *** [CMakeFiles/arsdk3_build.dir/build.make:73: parrot_arsdk/out/arsdk-native/staging/usr/lib] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:165: CMakeFiles/arsdk3_build.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< ros2_parrot_arsdk [27.9s, exited with code 2]

Summary: 0 packages finished [28.0s]
  1 package failed: ros2_parrot_arsdk
  1 package had stderr output: ros2_parrot_arsdk

I am using ROS2 Humble

**Comment by jeremyfix** [comment]
I believe your issue comes with `/bin/bash: line 1: python: command not found`

It seems your system is either completely missing the python interpreter or you just simply don't have the python -> python3 binding. 

You can simply check which is your case by typing, into a console : `python` or `python3` and see which one is missing.

**Comment by jeremyfix** [comment]
With nothing new on this issue, I close it;

Feel free to reopen if it makes sense.
