### ISSUE TITLE
Cmake Error: file does not recognize sub-command CHMOD

### ISSUE THREAD

**Issue by HongJooWon** [jeremyfix/ros2_parrot_arsdk#2]
Hello I tried to build as written : colcon build --packages-select ros2_parrot_arsdk

Then this error occured

```
Starting >>> ros2_parrot_arsdk
--- stderr: ros2_parrot_arsdk                         
CMake Error at cmake/fetch_arsdk.cmake:14 (file):
  file does not recognize sub-command CHMOD
Call Stack (most recent call first):
  CMakeLists.txt:39 (include)


---
Failed   <<< ros2_parrot_arsdk [0.93s, exited with code 1]

Summary: 0 packages finished [1.09s]
  1 package failed: ros2_parrot_arsdk
  1 package had stderr output: ros2_parrot_arsdk
```

the minimum version of cmake it says 3.5

**Comment by jeremyfix** [comment]
You are correct, the minimal version is actually 3.19 ; As indicated in the documentation (https://cmake.org/cmake/help/latest/command/file.html#chmod), the chmod has been introduced in the 3.19 release.

I updated the root CMakeLists.txt to fix the minimal version; Thanks for the notice.
